# Generated by Django 3.2.8 on 2021-10-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=50)),
                ('Proveedor', models.CharField(max_length=50)),
                ('Existencia', models.CharField(max_length=50)),
                ('DateOfJoining', models.DateField()),
                ('Categoria', models.CharField(max_length=50)),
                ('Descripción', models.CharField(max_length=500)),
            ],
        ),
    ]
